title: Fabio Henrique Shreiner 
description: Associado ao Mundo da Tecnologia e suas vertentes | Bacharel em Sistemas de Informação | Pós-Graduando em Engenharia de Redes de Computadores | Aspirante a Desenvolvedor Web e nas horas vagas Músico por paixão
show_downloads: false
show_github: true
google_analytics:
theme: jekyll-theme-cayman
